import "./globals.css";
export const metadata = {
  title: "@sam5.pro",
  description: "Generated by @sam5.pro",
};
import { Noto_Sans_Mono } from 'next/font/google';

const notoSansMono = Noto_Sans_Mono({
    weight: '400',
    subsets: ['latin'],
});


export default function RootLayout({ children }) {
  return (
      <html className={`${notoSansMono.className} dark`}>
          <body className="container">
              <div className="p-4 flex item-center justify-center m-4">
                  {children}
              </div>
          </body>
      </html>
  );
}
